version: '2'

services:

  postgres:
    image: sameersbn/postgresql:9.6-2
    container_name: postgres
    hostname: postgres
    ports:
    - 5432:5432
    environment:
    - DB_NAME=test_cpp_rest_db
    - PG_PASSWORD=postgres
