binary_name			:= domain.so
type				:= lib

include_folders			:= inc ../../lib/cpputest/install/include
library_folders			:= ../../lib/cpputest/install/lib
test_libs_to_link		:= :libCppUTest.a :libCppUTestExt.a

base_source_folders		:= src
test_source_folders		:= test

include ../module.mk
