binary_name			:= domain.so
type				:= lib

include_paths			:= inc \
                                   ../../lib/doctest/install/include
library_paths			:=
test_libs_to_link		:=

base_source_paths		:= src
test_source_paths		:= test

include ../../lib/generic_makefile/modular_makefile.mk
