binary_name			:= domain.so
type				:= lib

include_paths			:= inc ../../lib/cpputest/install/include
library_paths			:= ../../lib/cpputest/install/lib
test_libs_to_link		:= :libCppUTest.a :libCppUTestExt.a

base_source_paths		:= src
test_source_paths		:= test

include ../../lib/generic_makefile/modular_makefile.mk
