.PHONY: all
all:
	@$(MAKE) -s -C asio
	@$(MAKE) -s -C cpputest
	@$(MAKE) -s -C json
	@$(MAKE) -s -C kashmir
	@$(MAKE) -s -C pq
	@$(MAKE) -s -C pqxx
	@$(MAKE) -s -C restbed
	@$(MAKE) -s -C spdlog
	@$(MAKE) -s -C yaml

.PHONY: clean
clean:
	@$(MAKE) -s -C asio clean
	@$(MAKE) -s -C cpputest clean
	@$(MAKE) -s -C json clean
	@$(MAKE) -s -C kashmir clean
	@$(MAKE) -s -C pq clean
	@$(MAKE) -s -C pqxx clean
	@$(MAKE) -s -C restbed clean
	@$(MAKE) -s -C spdlog clean
	@$(MAKE) -s -C yaml clean
